parameters:
  - name: containerRegistry
  - name: appName
  - name: appVersion
  - name: sourceVersion

steps:
  - task: Docker@2
    displayName: Login to ACR ${{parameters.containerRegistry}}
    inputs:
      command: login
      containerRegistry: ${{parameters.containerRegistry}}

  - task: Docker@2
    displayName: Build ${{parameters.appName}} Docker Image
    inputs:
      command: build
      dockerfile: apps/${{parameters.appName}}/Dockerfile
      containerRegistry: ${{parameters.containerRegistry}}
      repository: react-apps/${{parameters.appName}}
      buildContext: .
      tags: ${{parameters.appVersion}}
      arguments: --build-arg "buildVersion=${{parameters.appVersion}}" --build-arg "commit=${{parameters.sourceVersion}}"

  - task: Docker@2
    displayName: Push ${{parameters.appName}} Docker Image
    inputs:
      command: push
      dockerfile: apps/${{parameters.appName}}/Dockerfile
      containerRegistry: ${{parameters.containerRegistry}}
      repository: react-apps/${{parameters.appName}}
      tags: ${{parameters.appVersion}}

  - task: Docker@2
    displayName: Logout of ACR
    inputs:
      command: logout
      containerRegistry: ${{parameters.containerRegistry}}
