parameters:
  - name: nodeVersion

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{parameters.nodeVersion}}
    displayName: 'Setup Node v.${{parameters.nodeVersion}}'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(npm_config_cache)
    displayName: Cache npm
    continueOnError: true

  - script: |
      npm ci
      npm run bootstrap:ci
    displayName: 'Install dependencies'
    env:
      CYPRESS_INSTALL_BINARY: '0'

  - script: |
      npm run build:production
    displayName: 'Build Production'
