apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.external.redisSecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.container.REDIS_PASSWORD | b64enc | quote }}
