{{ if eq .Values.network.ingress "nginx"}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-nginx
  namespace:  {{ .Release.Namespace }}
  labels:
    app:  {{ .Release.Name }}-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
    #ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    #kubernetes.io/ingress.class: {{ .Values.network.nginxClass }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  #ingressClassName: (( .Values.network.nginxClass }}
  #nginxIngressClass:  (( .Values.network.nginxIngressClass }}
  ingressClassName: dev-ingress-nginx
  tls:
    - hosts:
        - {{ .Values.network.host }}
      secretName: alcdev-net-tls
  rules:
    - host: {{ .Values.network.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: {{ .Values.service.port }}
{{end}}
