{{ if eq .Values.network.ingress "nginx"}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-nginx
  namespace:  {{ .Release.Namespace }}
  labels:
    app:  {{ .Release.Name }}-app
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "sameorigin";
    cert-manager.io/cluster-issuer: letsencrypt-dev
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ingressClassName: {{ .Release.Namespace }}-ingress-nginx
  tls:
    - hosts:
        - {{ .Values.network.host }}
      secretName: {{ .Values.network.secretName }}
  rules:
    - host: {{ .Values.network.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: {{ .Values.service.port }}
{{end}}
