apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data: 
  SCRP_EXPERIAN_API_KEY: {{ .Values.container.SCRP_EXPERIAN_API_KEY | b64enc | quote }}
  SCRP_API_KEY: {{ .Values.container.SCRP_API_KEY | b64enc | quote }}