{{ if eq .Values.network.ingress "nginx"}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress-nginx
  namespace:  {{ .Release.Namespace }}
  labels:
    app:  {{ .Release.Name }}-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dev
#    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # todo is-default-class and azure-load-balancer-internal seem like fishy properties.
    nginxClass.kubernetes.io/is-default-class: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ingressClassName: {{ .Release.Namespace }}-ingress-nginx
  tls:
    - hosts:
        - {{ .Values.network.host }}
      secretName: {{ .Values.network.secretName }}
  rules:
    - host: {{ .Values.network.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: {{ .Values.service.port }}
{{end}}
