apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ALCUMUS_PORTAL_SESSION_SECRET: {{ .Values.container.ALCUMUS_PORTAL_SESSION_SECRET | b64enc | quote }}
  ALCUMUS_PORTAL_MIXPANEL_TOKEN: {{ .Values.container.ALCUMUS_PORTAL_MIXPANEL_TOKEN | b64enc | quote }}